project:
  name: firstProject
  description: test
  version: 1.0.0

db:
  host: localhost
  port: 3306
  username: root
  password: root
  database: firstProject
  charset: utf8
  collation: utf8_general_ci